package org.acme.getting.started.dto;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-02-10T11:54:46.109+03:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "exportProcedureService",
                  wsdlLocation = "file:/media/hogmuzzle/D/interprocom/x5-portal/src/main/resources/wsdl/tektorg.wsdl",
                  targetNamespace = "http://api.tektorg.ru/procedures/soap")
public class ExportProcedureService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.tektorg.ru/procedures/soap", "exportProcedureService");
    public final static QName ExportProcedurePort = new QName("http://api.tektorg.ru/procedures/soap", "exportProcedurePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/media/hogmuzzle/D/interprocom/x5-portal/src/main/resources/wsdl/tektorg.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExportProcedureService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/media/hogmuzzle/D/interprocom/x5-portal/src/main/resources/wsdl/tektorg.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExportProcedureService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExportProcedureService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExportProcedureService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ExportProcedureService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExportProcedureService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExportProcedureService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ExportProcedurePort
     */
    @WebEndpoint(name = "exportProcedurePort")
    public ExportProcedurePort getExportProcedurePort() {
        return super.getPort(ExportProcedurePort, ExportProcedurePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExportProcedurePort
     */
    @WebEndpoint(name = "exportProcedurePort")
    public ExportProcedurePort getExportProcedurePort(WebServiceFeature... features) {
        return super.getPort(ExportProcedurePort, ExportProcedurePort.class, features);
    }

}
